ARG ELIXIR="1.14.2"
ARG ERLANG="25.1.2"
ARG ALPINE="3.16.2"

ARG BUILDER="hexpm/elixir:${ELIXIR}-erlang-${ERLANG}-alpine-${ALPINE}"
ARG RUNTIME="alpine:${ALPINE}"

FROM ${BUILDER} as builder

RUN apk add build-base curl

RUN curl -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mkdir /app
WORKDIR /app

COPY . .

RUN mix deps.get
RUN mix release

# 2. Release
FROM ${RUNTIME} as runtime

# Install dependencies
RUN apk add --no-cache --update bash openssl openssh-client ca-certificates libstdc++

# Prepare app dir & user
RUN mkdir /app
WORKDIR /app

# Fix permissions
RUN chown -R nobody: /app

COPY --from=builder --chown=nobody:root /app/_build/dev/rel/resvg ./
